
MAX_INDEX = 9
MIN_INDEX = 0
NUM_SQUARES = 3
NUM_BOXES = 3
EMPTY_SPACE = 0
SMALLEST_NUM = 1
LARGEST_NUM = 10
DEFAULT_LOCATION = -1
EASY_DIFFICULTY = 40
MEDIUM_DIFFICULTY = 45
HARD_DIFFICULTY = 50
INSANE_DIFFICULTY = 60
SEEDS = 10
